### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by awesomeconfig** [Prevter/GDOpenHack#53] opened 2024-02-04 09:01 UTC
**Describe the bug**
crash while launching the game.

here is the crash log : 
[2024-02-04_03-48-45.log](https://github.com/Prevter/GDOpenHack/files/14156142/2024-02-04_03-48-45.log)

**Comment by Prevter** [comment] 2024-02-04 09:48
Duplicate of #42

**Closed** 2024-02-24 21:30 UTC
Labels: bug
