### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by adamelvro** [Prevter/GDOpenHack#97] opened 2024-03-05 04:17 UTC
basically when i install openhack and restart the game, the game doesnt load and gets stuck on loading game resources
if someone knows how to solve it add me on discord: adamelvro

**Comment by adamelvro** [comment] 2024-03-05 04:21
![20240304221915_1](https://github.com/Prevter/GDOpenHack/assets/162271906/04c74ed9-430c-4732-8d39-dcb1f7c3a684)
![20240304221933_1](https://github.com/Prevter/GDOpenHack/assets/162271906/f1d8983b-547d-4d97-9f6b-de40858d9e53)

**Comment by Prevter** [comment] 2024-03-07 01:37
I'm guessing this was caused by Speedhack? Without additional information it's hard to tell, but it's hopefully fixed in 2.1.0 now

**Comment by adamelvro** [comment] 2024-03-07 01:47
Can i add you on discord so u can see??

**Comment by adamelvro** [comment] 2024-03-07 04:35
nvm i dont know how but it solved itself, thank you for the help tho, i
appreciate that u are a working guy <3

**Closed** 2024-03-07 07:48 UTC
Labels: bug
