### ISSUE TITLE
I set the speedhack to 10000x and it crashed... I deleted the mod, worked fine, reinstalled, and got a ton of errors. help.[Question]

### ISSUE THREAD

**Issue by RobotGato** [Prevter/GDOpenHack#95] opened 2024-03-03 19:12 UTC

**Comment by Prevter** [comment] 2024-03-04 00:50
Duplicate of #84
Check my answer in that issue, you'll be able to delete the save data for the mod.

Also, I'm making speedhack be always disabled when you launch the game, so this won't happen in the future update.

**Closed** 2024-03-04 16:05 UTC
Labels: question

**Comment by RobotGato** [comment] 2024-03-12 21:34
Thank you, this has been such a help!
